name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar requirements-dev
        run: pip install -r requirements-dev.txt  

      - name: Pruebas del corazon
        run: pytest                    

      - name: estilo y errores estaticos
        run: ruff check . 
